### ISSUE TITLE
CIF structure file format error

### ISSUE THREAD

**Issue by yx0516** [bytedance/Protenix#50]
When i use BioPython to read the CIF structure file predicted by Protenix. The following error happened:

![image](https://github.com/user-attachments/assets/a1919a82-a1d0-415e-bba5-a7e932c21f1c)

However the CIF file of other AF3-like models can be read normally by BioPython.

Please give a hand about this.

Thanks a lot.

**Comment by yx0516** [comment]
@LanLanBoom @lark @guanjq

**Comment by cloverzizi** [comment]
Hi @yx0516 ,
we previously hadn't included the occupancy field in the CIF file, but we have just updated the code. You can either pull the latest version of the code to run the inference or resubmit the task on the WebServer.

**Comment by yx0516** [comment]
Hi @cloverzizi,

I pull the latest version of code and run the inference.  And use the 'pip install .' to install the latest version and run the inference.
However the 'occupancy' field still not exists in the output CIF file. 
Is there something wrong?

**Comment by cloverzizi** [comment]
Hi @yx0516, 
We updated the code so that in Protenix v0.4.1, the inferred output CIF's `label_asym_id` is changed from formats like 'A0' to just 'A'. This adjustment ensures that when converting to PDB format, as long as the number of chains does not exceed 26, the requirement for single-character Chain IDs is met.
